# Generated by Django 3.1.7 on 2021-03-13 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instaClone', '0006_auto_20210313_0257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='photo',
            field=models.CharField(max_length=40000),
        ),
    ]
