# Generated by Django 3.1.7 on 2021-03-14 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instaClone', '0011_auto_20210313_1854'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='user',
        ),
        migrations.AddField(
            model_name='myuser',
            name='email',
            field=models.EmailField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='myuser',
            name='password',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='myuser',
            name='username',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
