# Generated by Django 3.1.7 on 2021-03-14 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instaClone', '0013_auto_20210314_1344'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_like_post',
            name='comment',
        ),
        migrations.AddField(
            model_name='user_like_post',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='instaClone.post'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='instaClone.post'),
        ),
        migrations.AlterField(
            model_name='post',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='instaClone.profile'),
        ),
        migrations.AlterField(
            model_name='user_like_comment',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='instaClone.comment'),
        ),
    ]
