# Generated by Django 3.1.7 on 2021-03-14 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instaClone', '0014_auto_20210314_1734'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='user_like_comment',
            unique_together={('user', 'comment')},
        ),
        migrations.AlterUniqueTogether(
            name='user_like_post',
            unique_together={('user', 'post')},
        ),
    ]
